import { useState } from "react";
import { Alert, Box, Button, Card, CardContent, Chip, Drawer, Stack, Typography } from "@mui/material";
import { AutoAwesome, Facebook, LinkOff, DeleteOutlined, SettingsOutlined, ThumbUpOutlined, VisibilityOutlined } from "@mui/icons-material";
import { useNavigate } from "react-router-dom";
import type { AnalysisReport, AnalysisStatus, FacebookPageSummary, WeeklyReport } from "@linora/shared";

type MetaReviewDashboardPageProps = { analysisStatus: AnalysisStatus | null; onDeleteData: () => Promise<void>; onDisconnect: () => Promise<void>; page: FacebookPageSummary; report: AnalysisReport; weeklyReport: WeeklyReport | null };
const format = (value: number | undefined) => value ? new Intl.NumberFormat("en-US").format(value) : "-";
const health = (score: number) => score >= 80 ? "Excellent" : score >= 65 ? "Good" : score >= 45 ? "Needs improvement" : "Needs attention";

export function MetaReviewDashboardPage({ analysisStatus, onDeleteData, onDisconnect, page, report, weeklyReport }: MetaReviewDashboardPageProps) {
  const navigate = useNavigate();
  const [managementOpen, setManagementOpen] = useState(false);
  const [action, setAction] = useState<"disconnect" | "delete" | null>(null);
  const [error, setError] = useState("");
  const insight = report.postingTimeInsight;
  const recommendation = report.aiContentRecommendation || "Linora is preparing recommendations from the latest Page data.";
  async function manage(kind: "disconnect" | "delete") { if (kind === "delete" && !window.confirm("Delete the selected Page connection, reports, and saved analytics data?")) return; setAction(kind); setError(""); try { if (kind === "disconnect") await onDisconnect(); else await onDeleteData(); setManagementOpen(false); } catch { setError("The action could not be completed. Please try again."); } finally { setAction(null); } }
  return <><Stack spacing={2} sx={{ pb: 19 }}>
    <Card><CardContent><Stack spacing={1.25}><Box sx={{ alignItems: "center", display: "flex", gap: 1 }}><Facebook sx={{ color: "#1877F2", fontSize: 30 }} /><Typography sx={{ fontSize: 21, fontWeight: 900 }}>{page.pageName}</Typography><Chip color="success" label="Authorized" size="small" /></Box><Typography color="text.secondary" sx={{ fontSize: 14 }}>Category: {page.category}</Typography><Typography color="text.secondary" sx={{ fontSize: 13 }}>{analysisStatus?.state === "refreshing" ? "Refreshing the latest Page data. Your previous report remains available." : "Linora uses data from this selected Page only and never posts on your behalf."}</Typography></Stack></CardContent></Card>
    <Card><CardContent><Stack direction="row" spacing={2} sx={{ alignItems: "center" }}><Box sx={{ alignItems: "center", border: "9px solid", borderColor: "primary.main", borderRadius: "50%", display: "flex", flex: "0 0 106px", height: 106, justifyContent: "center", width: 106 }}><Stack spacing={0} sx={{ textAlign: "center" }}><Typography sx={{ fontSize: 31, fontWeight: 900 }}>{report.healthScore}</Typography><Typography color="text.secondary" sx={{ fontSize: 12 }}>/100</Typography></Stack></Box><Stack spacing={0.6}><Typography color="text.secondary" sx={{ fontSize: 13, fontWeight: 800 }}>Page health overview</Typography><Typography sx={{ fontSize: 20, fontWeight: 900 }}>{health(report.healthScore)}</Typography><Typography color="text.secondary" sx={{ fontSize: 13, lineHeight: 1.5 }}>Based on the latest {insight?.basedOnPosts ?? 0} posts and {format(report.metrics?.engagements)} engagements.</Typography></Stack></Stack></CardContent></Card>
    <Card><CardContent><Stack spacing={1.25}><Box sx={{ alignItems: "center", display: "flex", gap: 0.75 }}><AutoAwesome color="primary" /><Typography sx={{ fontSize: 18, fontWeight: 900 }}>AI content recommendation</Typography></Box><Typography color="text.secondary" sx={{ fontSize: 14, lineHeight: 1.6, whiteSpace: "pre-line" }}>{recommendation}</Typography>{report.topPosts[0]?.excerpt ? <Box sx={{ bgcolor: "rgba(15,148,117,0.07)", borderLeft: "3px solid", borderColor: "primary.main", pl: 1.25, py: 0.75 }}><Typography color="primary.main" sx={{ fontSize: 12, fontWeight: 900 }}>Example from a top post</Typography><Typography color="text.secondary" sx={{ fontSize: 13, lineHeight: 1.5 }}>{report.topPosts[0].excerpt}</Typography></Box> : null}</Stack></CardContent></Card>
    <Card><CardContent><Stack spacing={1.1}><Typography sx={{ fontSize: 18, fontWeight: 900 }}>Best time to post</Typography><Typography sx={{ fontSize: 24, fontWeight: 900 }}>{insight?.bestTime || "Not enough data yet"}</Typography><Typography color="text.secondary" sx={{ fontSize: 14 }}>{insight?.basedOnPosts ? `Based on ${insight.basedOnPosts} recent posts.` : "Analyze more Page activity to calculate this insight."}</Typography></Stack></CardContent></Card>
    <Card><CardContent><Stack spacing={1.1}><Typography sx={{ fontSize: 18, fontWeight: 900 }}>Latest 7-day report</Typography><Box sx={{ display: "grid", gap: 1, gridTemplateColumns: "1fr auto" }}><Typography color="text.secondary"><VisibilityOutlined sx={{ fontSize: 18, mr: 1, verticalAlign: "text-bottom" }} />Reach</Typography><Typography sx={{ fontWeight: 900 }}>{format(weeklyReport?.metrics?.reach)}</Typography><Typography color="text.secondary"><ThumbUpOutlined sx={{ fontSize: 18, mr: 1, verticalAlign: "text-bottom" }} />Engagement</Typography><Typography sx={{ fontWeight: 900 }}>{format(weeklyReport?.metrics?.engagements)}</Typography></Box></Stack></CardContent></Card>
  </Stack><Box sx={{ backdropFilter: "blur(18px)", background: "linear-gradient(to top, rgba(248,246,240,.96), rgba(248,246,240,0))", bottom: 0, left: 0, pb: "calc(8px + env(safe-area-inset-bottom, 0px))", pt: .75, px: 2, position: "fixed", right: 0, zIndex: 20 }}><Stack direction="row" spacing={1} sx={{ maxWidth: 430, mx: "auto" }}><Button fullWidth onClick={() => navigate("/pages")} startIcon={<Facebook />} sx={{ borderColor: "#1877F2", color: "#1877F2" }} variant="outlined">Change Facebook Page</Button><Button aria-label="Manage data and permissions" onClick={() => setManagementOpen(true)} sx={{ borderColor: "#1877F2", color: "#1877F2", minWidth: 52 }} variant="outlined"><SettingsOutlined /></Button></Stack></Box>
  <Drawer anchor="bottom" onClose={() => setManagementOpen(false)} open={managementOpen} slotProps={{ paper: { sx: { borderRadius: "50% 50% 0 0 / 28px 28px 0 0", maxWidth: 430, mx: "auto", p: 2, pb: "calc(16px + env(safe-area-inset-bottom, 0px))", width: "100%" } } }}><Stack spacing={1.25}><Typography align="center" sx={{ fontSize: 16, fontWeight: 900 }}>Data and permissions</Typography><Typography color="text.secondary" sx={{ fontSize: 14, lineHeight: 1.55 }}>You can disconnect Facebook or delete your Linora data at any time.</Typography>{error ? <Alert severity="error">{error}</Alert> : null}<Button disabled={action !== null} fullWidth onClick={() => void manage("disconnect")} startIcon={<LinkOff />} sx={{ borderColor: "#1877F2", color: "#1877F2" }} variant="outlined">Disconnect Facebook</Button><Button color="error" disabled={action !== null} fullWidth onClick={() => void manage("delete")} startIcon={<DeleteOutlined />} variant="contained">Delete Linora data</Button></Stack></Drawer></>;
}
