import { useState } from "react";
import { Alert, Box, Button, Card, CardContent, Checkbox, FormControlLabel, Stack, Typography } from "@mui/material";
import { CheckCircle, Facebook, RadioButtonUnchecked, ShieldOutlined } from "@mui/icons-material";
import { useNavigate } from "react-router-dom";
import type { FacebookPageSummary } from "@linora/shared";
import { InsightCard } from "@linora/ui";
import { LoadingDots } from "../components/LoadingDots";

type MetaReviewPageSelectPageProps = { selectedPage: FacebookPageSummary | null; pages: FacebookPageSummary[]; onSelectPage: (page: FacebookPageSummary) => void; onAuthorize: () => Promise<void> };

export function MetaReviewPageSelectPage({ selectedPage, pages, onSelectPage, onAuthorize }: MetaReviewPageSelectPageProps) {
  const navigate = useNavigate();
  const [confirmed, setConfirmed] = useState(false);
  const [isAuthorizing, setIsAuthorizing] = useState(false);
  const [error, setError] = useState("");
  async function authorize() { if (!selectedPage || !confirmed) return; setIsAuthorizing(true); setError(""); try { await onAuthorize(); navigate("/dashboard"); } catch { setError("Unable to connect this Page. Please try again."); } finally { setIsAuthorizing(false); } }
  return <><Stack spacing={2} sx={{ pb: 27 }}><Stack spacing={0.5} sx={{ alignItems: "center", textAlign: "center" }}><Typography variant="h1">Choose a Facebook Page</Typography><Typography color="text.secondary" sx={{ fontSize: 15 }}>Select the Page Linora should analyze.</Typography></Stack><Card><CardContent><Stack spacing={1}><Typography sx={{ fontSize: 15, fontWeight: 900 }}>We use data only from the Page you select</Typography><Typography color="text.secondary" sx={{ fontSize: 14, lineHeight: 1.55 }}>Linora uses the selected Page's content, engagement, and relevant comments only to create reports. You can change Pages or disconnect later.</Typography></Stack></CardContent></Card>{error ? <Alert severity="error">{error}</Alert> : null}{pages.map((page) => <InsightCard key={page.pageId} title="Available Page" helper={`Category: ${page.category}`} value={<Box sx={{ alignItems: "center", display: "flex", gap: 1 }}><Facebook sx={{ color: "#1877F2", fontSize: 34 }} />{page.pageName}</Box>} action={<Button fullWidth onClick={() => onSelectPage(page)} startIcon={selectedPage?.pageId === page.pageId ? <CheckCircle /> : <RadioButtonUnchecked />} sx={selectedPage?.pageId === page.pageId ? { bgcolor: "#1877F2", "&:hover": { bgcolor: "#166FE5" } } : { borderColor: "#1877F2", color: "#1877F2" }} variant={selectedPage?.pageId === page.pageId ? "contained" : "outlined"}>{selectedPage?.pageId === page.pageId ? "Page selected" : "Select this Page"}</Button>} />)}</Stack><Box sx={{ backdropFilter: "blur(18px)", background: "linear-gradient(to top, rgba(248, 246, 240, 0.96), rgba(248, 246, 240, 0))", bottom: 0, left: 0, pb: "calc(8px + env(safe-area-inset-bottom, 0px))", pt: 0.75, px: 2, position: "fixed", right: 0, zIndex: 20 }}><Stack spacing={1} sx={{ maxWidth: 430, mx: "auto" }}><Card><CardContent><Stack spacing={1}><Typography sx={{ fontSize: 15, fontWeight: 900 }}>Confirm before continuing</Typography><FormControlLabel control={<Checkbox checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} />} label={<Typography color="text.secondary" sx={{ fontSize: 14, lineHeight: 1.45 }}>I manage this Page or have permission to manage it, and I authorize Linora to analyze the selected Page.</Typography>} sx={{ alignItems: "flex-start", m: 0 }} /><Typography color="text.secondary" sx={{ fontSize: 13 }}>Linora will not post, reply to, or edit this Page automatically.</Typography></Stack></CardContent></Card><Button disabled={!selectedPage || !confirmed || isAuthorizing} fullWidth onClick={() => void authorize()} size="large" startIcon={isAuthorizing ? <LoadingDots color="currentColor" size={7} /> : <ShieldOutlined />} variant="contained">{isAuthorizing ? "Opening analytics" : "Authorize and open analytics"}</Button></Stack></Box></>;
}
